### ISSUE TITLE
Tooltip positioning does not work correctly on the right side of the document 

### ISSUE THREAD

**Issue by mateuszsikora** [FluffyLabs/graypaper-reader#75]
When the note-related text is on the right side of the document then the tooltip is rendered under the right section of the app:

<img width="911" alt="Screenshot 2024-10-01 at 22 25 16" src="https://github.com/user-attachments/assets/9ef2b279-6183-457c-8a9b-8d6362272a1a">

**Comment by tomusdrw** [comment]
Overall the notes should not overlay the document at all, cause the thing happens on the left hand side as well (see screenshot).

<img width="344" alt="image" src="https://github.com/user-attachments/assets/dd5c8667-6f7a-4046-bfa7-4c845809f4a3">

This can be partially alleviated by #83 (showing/hiding annotations).

Other options are:
1. Make annotations transparent on hover (so that you can see through them).
2. Allow drag&dropping annotations (to move them out of the way)
3. Collapse annotations to small icons - clicking them expands the full note (similar to how pdf readers does that).

**Comment by wirednkod** [comment]
@tomusdrw Should this close? Or more things should be addressed?

**Comment by tomusdrw** [comment]
Yes! Thank you @wirednkod it works pretty well now, if we run into similar thing in the future we can always open a new one.
